# Generated by Django 5.1.4 on 2025-06-10 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0024_remove_vaccination_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255)),
                ('subheading', models.CharField(blank=True, max_length=500)),
                ('image', models.ImageField(upload_to='blog_images/')),
                ('content', models.TextField(help_text='Use Markdown or HTML for rich formatting.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
