# Generated by Django 5.1.4 on 2025-08-20 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0025_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='home_banner',
            name='category',
            field=models.CharField(blank=True, choices=[('vaccination', 'Vaccination'), ('video_consultation', 'Video Consultation'), ('general_consultation', 'General Consultation'), ('grooming', 'Grooming'), ('boarding', 'Boarding'), ('lab_test', 'Lab Test')], max_length=50, null=True),
        ),
    ]
