# Generated by Django 5.1.4 on 2025-04-06 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='pet_photos/')),
                ('pet_type', models.CharField(choices=[('dog', 'dog'), ('cat', 'cat')], max_length=10)),
                ('breed', models.CharField(max_length=255)),
                ('born_date', models.DateField()),
                ('age', models.IntegerField()),
                ('productive_status', models.CharField(max_length=255)),
                ('weight', models.FloatField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='medical_report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('report', models.TextField()),
                ('date', models.DateField()),
                ('pet', models.ManyToManyField(to='pet.pet')),
            ],
        ),
        migrations.CreateModel(
            name='lab_report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.TextField()),
                ('date', models.DateField()),
                ('pet', models.ManyToManyField(to='pet.pet')),
            ],
        ),
        migrations.CreateModel(
            name='food_preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference', models.TextField()),
                ('pet', models.ManyToManyField(to='pet.pet')),
            ],
        ),
        migrations.CreateModel(
            name='appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('payment_status', models.BooleanField(default=False)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor')),
                ('pet', models.ManyToManyField(to='pet.pet')),
            ],
        ),
        migrations.CreateModel(
            name='vaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('additional_questions', models.JSONField()),
                ('date_given', models.DateField()),
                ('pet', models.ManyToManyField(to='pet.pet')),
            ],
        ),
    ]
