# Generated by Django 5.1.4 on 2025-04-09 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0007_rename_address_customer_address'),
        ('pet', '0002_rename_vaccination_pet_vaccination'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='symptom',
            field=models.ManyToManyField(to='masters.symptom'),
        ),
    ]
