# Generated by Django 5.1.4 on 2025-04-10 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0007_rename_address_customer_address'),
        ('pet', '0006_order_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='breed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.dog_breed'),
        ),
    ]
