# Generated by Django 5.1.4 on 2025-04-11 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0009_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='test_booking',
            name='report',
            field=models.FileField(blank=True, null=True, upload_to='reports/'),
        ),
    ]
