# Generated by Django 5.1.4 on 2025-04-13 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0012_remove_order_products_order_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation_appointment',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
