# Generated by Django 5.1.4 on 2025-04-14 12:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daycare', '0005_delete_day_care_booking'),
        ('pet', '0013_consultation_appointment_is_online'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='day_care_booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('drop_off', models.BooleanField()),
                ('pick_up', models.BooleanField()),
                ('food_selection', models.TextField()),
                ('payment_status', models.BooleanField(default=False)),
                ('half_day_on_checkin', models.BooleanField(default=False)),
                ('half_day_on_checkout', models.BooleanField(default=False)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('daycare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daycare.day_care')),
                ('pets', models.ManyToManyField(to='pet.pet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
