# Generated by Django 5.1.4 on 2025-04-15 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0019_food_menu'),
        ('pet', '0014_day_care_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='day_care_booking',
            old_name='half_day_on_checkin',
            new_name='full_day',
        ),
        migrations.RenameField(
            model_name='day_care_booking',
            old_name='half_day_on_checkout',
            new_name='half_day',
        ),
        migrations.RemoveField(
            model_name='day_care_booking',
            name='food_selection',
        ),
        migrations.AddField(
            model_name='day_care_booking',
            name='food_selection',
            field=models.ManyToManyField(to='masters.food_menu'),
        ),
    ]
