# Generated by Django 5.1.4 on 2025-04-16 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_delete_consultation_booking'),
        ('masters', '0020_consultation_type_online_consultation_type'),
        ('pet', '0016_remove_day_care_booking_drop_off_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation_appointment',
            name='is_online',
        ),
        migrations.AddField(
            model_name='consultation_appointment',
            name='consultation_type',
            field=models.ManyToManyField(to='masters.consultation_type'),
        ),
        migrations.CreateModel(
            name='online_consultation_appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('payment_status', models.BooleanField(default=False)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor')),
                ('online_consultation_type', models.ManyToManyField(to='masters.online_consultation_type')),
                ('pet', models.ManyToManyField(to='pet.pet')),
                ('symptom', models.ManyToManyField(to='masters.symptom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
