# Generated by Django 5.1.4 on 2025-04-17 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0018_remove_cart_content_type_remove_cart_object_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test_booking',
            name='report',
        ),
        migrations.CreateModel(
            name='ConsultationAppointmentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='reports/consultation/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='pet.consultation_appointment')),
            ],
        ),
        migrations.CreateModel(
            name='OnlineConsultationAppointmentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='reports/online_consultation/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='pet.online_consultation_appointment')),
            ],
        ),
        migrations.CreateModel(
            name='TestBookingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='reports/test_booking/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='pet.test_booking')),
            ],
        ),
    ]
