# Generated by Django 5.1.4 on 2025-04-17 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0019_remove_test_booking_report_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onlineconsultationappointmentreport',
            name='appointment',
        ),
        migrations.RemoveField(
            model_name='testbookingreport',
            name='booking',
        ),
        migrations.DeleteModel(
            name='ConsultationAppointmentReport',
        ),
        migrations.DeleteModel(
            name='OnlineConsultationAppointmentReport',
        ),
        migrations.DeleteModel(
            name='TestBookingReport',
        ),
    ]
