# Generated by Django 5.1.4 on 2025-04-17 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0019_remove_test_booking_report_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test_booking',
            name='user',
        ),
    ]
