# Generated by Django 5.1.4 on 2025-04-19 11:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0021_remove_food_menu_price'),
        ('pet', '0022_test_booking_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='service_booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('address', models.TextField(blank=True, null=True)),
                ('at_home', models.BooleanField(default=False)),
                ('payment_status', models.BooleanField(default=False)),
                ('pets', models.ManyToManyField(to='pet.pet')),
                ('services', models.ManyToManyField(to='masters.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
