# Generated by Django 5.1.4 on 2025-04-19 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0023_service_booking'),
        ('serviceprovider', '0003_delete_service_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_booking',
            name='service_provider',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='serviceprovider.service_provider'),
            preserve_default=False,
        ),
    ]
