# Generated by Django 5.1.4 on 2025-04-21 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0021_remove_food_menu_price'),
        ('pet', '0025_alter_consultation_appointment_doctor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='masters.customer_address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test_booking',
            name='address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='masters.customer_address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vaccination_appointment',
            name='address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='masters.customer_address'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service_booking',
            name='address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='masters.customer_address'),
            preserve_default=False,
        ),
    ]
