# Generated by Django 5.1.4 on 2025-04-21 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0021_remove_food_menu_price'),
        ('pet', '0026_order_address_test_booking_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.customer_address'),
        ),
    ]
