# Generated by Django 5.1.4 on 2025-05-02 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0027_alter_order_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='day_care_booking',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('accepted', 'Accepted'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='open', max_length=10),
        ),
    ]
