# Generated by Django 5.1.4 on 2025-05-02 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0028_day_care_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation_appointment',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('accepted', 'Accepted'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='open', max_length=10),
        ),
        migrations.AddField(
            model_name='online_consultation_appointment',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('accepted', 'Accepted'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='open', max_length=10),
        ),
        migrations.AddField(
            model_name='service_booking',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('accepted', 'Accepted'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='open', max_length=10),
        ),
        migrations.AddField(
            model_name='test_booking',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('accepted', 'Accepted'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='open', max_length=10),
        ),
        migrations.AddField(
            model_name='vaccination_appointment',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('accepted', 'Accepted'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='open', max_length=10),
        ),
    ]
