# Generated by Django 5.1.4 on 2025-05-07 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0030_consultation_appointment_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='consultation_appointment',
            name='booking_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='day_care_booking',
            name='booking_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='online_consultation_appointment',
            name='booking_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='service_booking',
            name='booking_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='test_booking',
            name='booking_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='vaccination_appointment',
            name='booking_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
