# Generated by Django 5.1.4 on 2025-05-27 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daycare', '0008_day_care_is_active'),
        ('masters', '0024_remove_vaccination_image'),
        ('pet', '0031_bookingsequence_consultation_appointment_booking_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day_care_booking',
            name='daycare',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='daycare.day_care'),
        ),
        migrations.AlterField(
            model_name='service_booking',
            name='services',
            field=models.ManyToManyField(blank=True, null=True, to='masters.service'),
        ),
    ]
