# Generated by Django 5.1.4 on 2025-05-29 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0024_remove_vaccination_image'),
        ('pet', '0032_alter_day_care_booking_daycare_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation_appointment',
            name='consultation_type',
        ),
        migrations.RemoveField(
            model_name='consultation_appointment',
            name='pet',
        ),
        migrations.RemoveField(
            model_name='consultation_appointment',
            name='symptom',
        ),
        migrations.RemoveField(
            model_name='day_care_booking',
            name='pets',
        ),
        migrations.RemoveField(
            model_name='online_consultation_appointment',
            name='online_consultation_type',
        ),
        migrations.RemoveField(
            model_name='online_consultation_appointment',
            name='pet',
        ),
        migrations.RemoveField(
            model_name='online_consultation_appointment',
            name='symptom',
        ),
        migrations.RemoveField(
            model_name='service_booking',
            name='pets',
        ),
        migrations.RemoveField(
            model_name='service_booking',
            name='services',
        ),
        migrations.RemoveField(
            model_name='test_booking',
            name='pet',
        ),
        migrations.RemoveField(
            model_name='test_booking',
            name='test',
        ),
        migrations.RemoveField(
            model_name='vaccination_appointment',
            name='pet',
        ),
        migrations.RemoveField(
            model_name='vaccination_appointment',
            name='vaccination',
        ),
        migrations.AddField(
            model_name='consultation_appointment',
            name='consultation_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='masters.consultation_type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consultation_appointment',
            name='pet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pet.pet'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consultation_appointment',
            name='symptom',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='masters.symptom'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='day_care_booking',
            name='pets',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pet.pet'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='online_consultation_appointment',
            name='online_consultation_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='masters.online_consultation_type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='online_consultation_appointment',
            name='pet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pet.pet'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='online_consultation_appointment',
            name='symptom',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='masters.symptom'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service_booking',
            name='pets',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pet.pet'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service_booking',
            name='services',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.service'),
        ),
        migrations.AddField(
            model_name='test_booking',
            name='pet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pet.pet'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test_booking',
            name='test',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='masters.test'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vaccination_appointment',
            name='pet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pet.pet'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vaccination_appointment',
            name='vaccination',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='masters.vaccination'),
            preserve_default=False,
        ),
    ]
