# Generated by Django 5.1.4 on 2025-05-30 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0033_remove_consultation_appointment_consultation_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation_appointment',
            name='pet',
        ),
        migrations.RemoveField(
            model_name='day_care_booking',
            name='pets',
        ),
        migrations.RemoveField(
            model_name='online_consultation_appointment',
            name='pet',
        ),
        migrations.RemoveField(
            model_name='service_booking',
            name='pets',
        ),
        migrations.RemoveField(
            model_name='test_booking',
            name='pet',
        ),
        migrations.RemoveField(
            model_name='vaccination_appointment',
            name='pet',
        ),
        migrations.AddField(
            model_name='consultation_appointment',
            name='pet',
            field=models.ManyToManyField(to='pet.pet'),
        ),
        migrations.AddField(
            model_name='day_care_booking',
            name='pets',
            field=models.ManyToManyField(to='pet.pet'),
        ),
        migrations.AddField(
            model_name='online_consultation_appointment',
            name='pet',
            field=models.ManyToManyField(to='pet.pet'),
        ),
        migrations.AddField(
            model_name='service_booking',
            name='pets',
            field=models.ManyToManyField(to='pet.pet'),
        ),
        migrations.AddField(
            model_name='test_booking',
            name='pet',
            field=models.ManyToManyField(to='pet.pet'),
        ),
        migrations.AddField(
            model_name='vaccination_appointment',
            name='pet',
            field=models.ManyToManyField(to='pet.pet'),
        ),
    ]
