# Generated by Django 5.1.4 on 2025-05-31 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0035_pastvaccination'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastvaccination',
            name='pet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pet.pet'),
            preserve_default=False,
        ),
    ]
