# Generated by Django 5.1.4 on 2025-05-31 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0024_remove_vaccination_image'),
        ('pet', '0036_pastvaccination_pet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation_appointment',
            name='symptom',
        ),
        migrations.RemoveField(
            model_name='online_consultation_appointment',
            name='symptom',
        ),
        migrations.AddField(
            model_name='consultation_appointment',
            name='symptom',
            field=models.ManyToManyField(to='masters.symptom'),
        ),
        migrations.AddField(
            model_name='online_consultation_appointment',
            name='symptom',
            field=models.ManyToManyField(to='masters.symptom'),
        ),
    ]
