# Generated by Django 5.1.4 on 2025-06-12 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0037_remove_consultation_appointment_symptom_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet_vaccination',
            name='additional_questions',
        ),
    ]
