# Generated by Django 5.1.4 on 2025-04-06 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='day_care',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('images', models.ImageField(blank=True, null=True, upload_to='daycare_photos/')),
                ('location', models.TextField()),
                ('description', models.TextField()),
                ('price_per_hour', models.FloatField()),
                ('price_per_day', models.FloatField()),
                ('rating', models.FloatField()),
                ('amenities', models.ManyToManyField(to='masters.amenity')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='day_care_booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('drop_off', models.BooleanField()),
                ('pick_up', models.BooleanField()),
                ('food_selection', models.TextField()),
                ('payment_status', models.BooleanField(default=False)),
                ('daycare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daycare.day_care')),
            ],
        ),
    ]
