# Generated by Django 5.1.4 on 2025-04-06 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('daycare', '0001_initial'),
        ('pet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='day_care_booking',
            name='pets',
            field=models.ManyToManyField(to='pet.pet'),
        ),
    ]
