# Generated by Django 5.1.4 on 2025-04-08 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daycare', '0002_initial'),
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day_care',
            name='amenities',
            field=models.ManyToManyField(blank=True, null=True, to='masters.amenity'),
        ),
        migrations.AlterField(
            model_name='day_care',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='day_care',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='day_care',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='day_care',
            name='price_per_day',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='day_care',
            name='price_per_hour',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='day_care',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
