# Generated by Django 5.1.4 on 2025-04-14 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daycare', '0004_day_care_booking_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='day_care_booking',
        ),
    ]
