# Generated by Django 5.1.4 on 2025-04-15 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daycare', '0005_delete_day_care_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='day_care',
            old_name='price_per_day',
            new_name='price_full_day',
        ),
        migrations.RenameField(
            model_name='day_care',
            old_name='price_per_hour',
            new_name='price_half_day',
        ),
    ]
