# Generated by Django 5.1.4 on 2025-04-18 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daycare', '0006_rename_price_per_day_day_care_price_full_day_and_more'),
        ('masters', '0021_remove_food_menu_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayCareFoodMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_price', models.FloatField()),
                ('daycare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daycare.day_care')),
                ('food_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.food_menu')),
            ],
            options={
                'unique_together': {('daycare', 'food_menu')},
            },
        ),
    ]
