# Generated by Django 5.1.4 on 2025-04-22 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daycare', '0007_daycarefoodmenu'),
    ]

    operations = [
        migrations.AddField(
            model_name='day_care',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
