# Generated by Django 5.1.4 on 2025-04-19 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serviceprovider', '0002_remove_service_provider_mobile_no'),
    ]

    operations = [
        migrations.DeleteModel(
            name='service_booking',
        ),
    ]
