# Generated by Django 5.1.4 on 2025-04-30 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceprovider', '0003_delete_service_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_provider',
            name='image',
            field=models.ImageField(default=1, upload_to='doctor_images/'),
            preserve_default=False,
        ),
    ]
