# Generated by Django 5.1.4 on 2025-04-30 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serviceprovider', '0004_service_provider_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service_provider',
            name='full_name',
        ),
    ]
