# Generated by Django 5.1.4 on 2025-04-09 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_doctor_available_from_doctor_available_to'),
    ]

    operations = [
        migrations.DeleteModel(
            name='consultation_booking',
        ),
    ]
