# Generated by Django 5.1.4 on 2025-04-17 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_consultationappointmentreport_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testbookingreport',
            old_name='file',
            new_name='report',
        ),
    ]
