# Generated by Django 5.1.4 on 2025-05-02 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0007_consultationappointmentreport_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultationappointmentreport',
            name='status',
        ),
        migrations.RemoveField(
            model_name='onlineconsultationappointmentreport',
            name='status',
        ),
        migrations.RemoveField(
            model_name='testbookingreport',
            name='status',
        ),
    ]
