# Generated by Django 5.1.4 on 2025-05-06 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0009_alter_doctor_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apoinments_video_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appoinment_id', models.BigIntegerField()),
                ('call_id', models.BigIntegerField()),
                ('token', models.BigIntegerField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor')),
            ],
        ),
    ]
