# Generated by Django 5.1.4 on 2025-05-06 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0010_apoinments_video_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apoinments_video_details',
            name='appoinment_id',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='apoinments_video_details',
            name='call_id',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='apoinments_video_details',
            name='doctor',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='apoinments_video_details',
            name='token',
            field=models.CharField(max_length=150),
        ),
    ]
