# Generated by Django 5.1.4 on 2025-05-30 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0011_alter_apoinments_video_details_appoinment_id_and_more'),
        ('pet', '0035_pastvaccination'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccinationBookingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.FileField(upload_to='reports/test_booking/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='pet.vaccination_appointment')),
            ],
        ),
    ]
